[litex]
github_user = "lschuermann"
github_repo = "litex"
git_revision = "3325aabd46dd4698903f0647ac154fef8ba32b60"
github_archive_nix_hash = "0qyb6vqg0fn9qdmdqax1sqsmd5c7s0j725yipmp7lfk7c6dv1qz3"

[litex-boards]
github_user = "litex-hub"
github_repo = "litex-boards"
git_revision = "f18b10d1edb4e162a77972e2e9c5bad54ca00788"
github_archive_nix_hash = "1n30phdhmx2w3zn0793k2a6wkk5d7lpd918ksf0qbsi14c8v3aca"

[liteeth]
github_user = "enjoy-digital"
github_repo = "liteeth"
git_revision = "1db5299a62638b66f9b887baac78f59573cde2ac"
github_archive_nix_hash = "19zi465k40g3dzknb2f3zc6r2bvb1hr3vay6vgiyp1fv8jcykfx4"

[litedram]
github_user = "enjoy-digital"
github_repo = "litedram"
git_revision = "9e9c83ce40ae6ea50546b6cc307b9c581ff046ab"
github_archive_nix_hash = "0zqg8f1725dy2z23cp84lvsa7g88v3zdbyc6pa9dhn9x4hwkwgja"

[litehyperbus]
github_user = "litex-hub"
github_repo = "litehyperbus"
git_revision = "9f118e83c819a20e1348d295cc9a251cc006f8f8"
github_archive_nix_hash = "0sziiqjs1z526zv9zrf5mpgf8inw7pqycrk6538srza9818bgdr9"

[liteiclink]
github_user = "enjoy-digital"
github_repo = "liteiclink"
git_revision = "3d8ecdbcf9f0260292221ff63b0ad3f5e409a955"
github_archive_nix_hash = "0blvgg26pf174nl8gi91a3aahalav0l4fcqdyphhc2i49iz63rnr"

[litepcie]
github_user = "enjoy-digital"
github_repo = "litepcie"
git_revision = "5e6b2decf1b616a442b9fedafea095aa757990c9"
github_archive_nix_hash = "1wjyy1j28zfmwdamrkncczzc5jl21jfs6fc0n2sp2azjzhj6jsvm"

[litescope]
github_user = "enjoy-digital"
github_repo = "litescope"
git_revision = "08072a78ba1157d106d305bdc93cd9c5d35bab98"
github_archive_nix_hash = "112370chh6vbiiiay20h7h5mdxwackxlqpvmq7s5d5l16c0mdzp7"

[litesdcard]
github_user = "enjoy-digital"
github_repo = "litesdcard"
git_revision = "4edf05e627a8b5f03e632215accec8ab588737e3"
github_archive_nix_hash = "IfD6wYT3+b/bY+LwktDIrcO+kbbVi+oeHeK3Qiitcbw="

[litespi]
github_user = "litex-hub"
github_repo = "litespi"
git_revision = "4cb907881bb75999e4c6bb68e211dd5cfc301de9"
github_archive_nix_hash = "137zb64fa8092ivm39big92s0lspm4kdkshp3in8fwilybzjmkgv"

[litevideo]
github_user = "enjoy-digital"
github_repo = "litevideo"
git_revision = "41f30143075ece3fff5c33a332ed067d1837cbb3"
github_archive_nix_hash = "06vw4rn8xby8is13275bmkrxlwp3wlznbdqfay78a5m8bp73kypy"

[pythondata-misc-tapcfg]
github_user = "litex-hub"
github_repo = "pythondata-misc-tapcfg"
git_revision = "0e6809132b7a42d26fc148b2b5e54ede8d6021ab"
github_archive_nix_hash = "182m452iclahx1ipic0x7q4c9w33w6vfm9lz8zbx39zli9dg7l03"

[pythondata-software-compiler_rt]
github_user = "litex-hub"
github_repo = "pythondata-software-compiler_rt"
git_revision = "fcb03245613ccf3079cc833a701f13d0beaae09d"
github_archive_nix_hash = "06pz4zs8wizx1yp5sv07l9gs71brlr4c8jrxszp0jq7h2g35zyxk"

[pythondata-cpu-serv]
github_user = "litex-hub"
github_repo = "pythondata-cpu-serv"
git_revision = "da5ad1e992e1a61926ad513b6f88b3a16867b5b9"
github_archive_nix_hash = "0awqylqj11nkzashk3wlbjl8d8lx7a3lxaa304jrbgn6zr13x1xx"

[valentyusb-hw_cdc_eptri]
github_user = "litex-hub"
github_repo = "valentyusb"
git_revision = "912d8e6dc72d45e092e608ffcaabfeaaa6d4580f"
github_archive_nix_hash = "0c3zmhydbwd5vdmxlrbyc8iasf2ai28brm0fnkxrp4w5w1gd9ja6"

[pythondata-cpu-vexriscv]
version = "20210924"
tarball_url = "https://github.com/lschuermann/litex-vexriscv-custom/releases/download/2021092400/generated.tar.gz"
tarball_nix_hash = "1kg5jz26r3245n2396jn5m5xq8dj0pwngn3aib5rj2bfwrvbsvw5"